import { ImageData } from '../types';

export const IMAGES: ImageData[] = [
    { name: 'Affe', url: '/images/affe.svg', letter: 'a' },
    { name: 'Ananas', url: '/images/ananas.svg', letter: 'a' },
    { name: 'Apfel', url: '/images/apfel.svg', letter: 'a' },
    { name: 'Ampel', url: '/images/ampel.svg', letter: 'a' },
    { name: 'Anker', url: '/images/anker.svg', letter: 'a' },
    { name: 'Auto', url: '/images/auto.svg', letter: 'au' },
    { name: 'Ärztin', url: '/images/aerztin.svg', letter: 'ä' },
    { name: 'Blume', url: '/images/blume.svg', letter: 'b' },
    { name: 'Baum', url: '/images/baum.svg', letter: 'b' },
    { name: 'Banane', url: '/images/banane.svg', letter: 'b' },
    { name: 'Birne', url: '/images/birne.svg', letter: 'b' },
    { name: 'Brot', url: '/images/brot.svg', letter: 'b' },
    { name: 'Brezel', url: '/images/brezel.svg', letter: 'b' },
    { name: 'Berg', url: '/images/berg.svg', letter: 'b' },
    { name: 'Bus', url: '/images/bus.svg', letter: 'b' },
    { name: 'Blitz', url: '/images/blitz.svg', letter: 'b' },
    { name: 'Brille', url: '/images/brille.svg', letter: 'b' },
    { name: 'Bett', url: '/images/bett.svg', letter: 'b' },
    { name: 'Clown', url: '/images/clown.svg', letter: 'c' },
    { name: 'Drache', url: '/images/drache.svg', letter: 'd' },
    { name: 'Dinosaurier', url: '/images/dinosaurier.svg', letter: 'd' },
    { name: 'Elefant', url: '/images/elefant.svg', letter: 'e' },
    { name: 'Ente', url: '/images/ente.svg', letter: 'e' },
    { name: 'Erdbeere', url: '/images/erdbeere.svg', letter: 'e' },
    { name: 'Eule', url: '/images/eule.svg', letter: 'eu' },
    { name: 'Einhorn', url: '/images/einhorn.svg', letter: 'ei' },
    { name: 'Eisbär', url: '/images/eisbaer.svg', letter: 'ei' },
    { name: 'Ei', url: '/images/ei.svg', letter: 'ei' },
    { name: 'Eis', url: '/images/eis.svg', letter: 'ei' },
    { name: 'Eimer', url: '/images/eimer.svg', letter: 'ei' },
    { name: 'Feuerwehrfrau', url: '/images/feuerwehrfrau.svg', letter: 'f' },
    { name: 'Füße', url: '/images/fuesse.svg', letter: 'f' },
    { name: 'Fuchs', url: '/images/fuchs.svg', letter: 'f' },
    { name: 'Flamingo', url: '/images/flamingo.svg', letter: 'f' },
    { name: 'Flügel', url: '/images/fluegel.svg', letter: 'f' },
    { name: 'Frosch', url: '/images/frosch.svg', letter: 'f' },
    { name: 'Fisch', url: '/images/fisch.svg', letter: 'f' },
    { name: 'Feuerwehr', url: '/images/feuerwehr.svg', letter: 'f' },
    { name: 'Fahrrad', url: '/images/fahrrad.svg', letter: 'f' },
    { name: 'Flugzeug', url: '/images/flugzeug.svg', letter: 'f' },
    { name: 'Fußball', url: '/images/fussball.svg', letter: 'f' },
    { name: 'Fächer', url: '/images/faecher.svg', letter: 'f' },
    { name: 'Fenster', url: '/images/fenster.svg', letter: 'f' },
    { name: 'Gespenst', url: '/images/gespenst.svg', letter: 'g' },
    { name: 'Giraffe', url: '/images/giraffe.svg', letter: 'g' },
    { name: 'Geschenk', url: '/images/geschenk.svg', letter: 'g' },
    { name: 'Geldbeutel', url: '/images/geldbeutel.svg', letter: 'g' },
    { name: 'Glocke', url: '/images/glocke.svg', letter: 'g' },
    { name: 'Geige', url: '/images/geige.svg', letter: 'g' },
    { name: 'Herz', url: '/images/herz.svg', letter: 'h' },
    { name: 'Hand', url: '/images/hand.svg', letter: 'h' },
    { name: 'Hund', url: '/images/hund.svg', letter: 'h' },
    { name: 'Hirsch', url: '/images/hirsch.svg', letter: 'h' },
    { name: 'Hase', url: '/images/hase.svg', letter: 'h' },
    { name: 'Huhn', url: '/images/huhn.svg', letter: 'h' },
    { name: 'Heidelbeere', url: '/images/heidelbeere.svg', letter: 'h' },
    { name: 'Haus', url: '/images/haus.svg', letter: 'h' },
    { name: 'Hubschrauber', url: '/images/hubschrauber.svg', letter: 'h' },
    { name: 'Hose', url: '/images/hose.svg', letter: 'h' },
    { name: 'Hut', url: '/images/hut.svg', letter: 'h' },
    { name: 'Handy', url: '/images/handy.svg', letter: 'h' },
    { name: 'Hammer', url: '/images/hammer.svg', letter: 'h' },
    { name: 'Igel', url: '/images/igel.svg', letter: 'i' },
    { name: 'Insel', url: '/images/insel.svg', letter: 'i' },
    { name: 'jonglieren', url: '/images/jonglieren.svg', letter: 'j' },
    { name: 'krank', url: '/images/krank.svg', letter: 'k' },
    { name: 'kalt', url: '/images/kalt.svg', letter: 'k' },
    { name: 'Köchin', url: '/images/koechin.svg', letter: 'k' },
    { name: 'Katze', url: '/images/katze.svg', letter: 'k' },
    { name: 'Kuh', url: '/images/kuh.svg', letter: 'k' },
    { name: 'Känguru', url: '/images/kaenguru.svg', letter: 'k' },
    { name: 'Krähe', url: '/images/kraehe.svg', letter: 'k' },
    { name: 'Krokodil', url: '/images/krokodil.svg', letter: 'k' },
    { name: 'Kaktus', url: '/images/kaktus.svg', letter: 'k' },
    { name: 'Kirsche', url: '/images/kirsche.svg', letter: 'k' },
    { name: 'Käse', url: '/images/kaese.svg', letter: 'k' },
    { name: 'Kuchen', url: '/images/kuchen.svg', letter: 'k' },
    { name: 'Kaffee', url: '/images/kaffee.svg', letter: 'k' },
    { name: 'Kirche', url: '/images/kirche.svg', letter: 'k' },
    { name: 'Kleid', url: '/images/kleid.svg', letter: 'k' },
    { name: 'Krone', url: '/images/krone.svg', letter: 'k' },
    { name: 'Kopfhörer', url: '/images/kopfhoerer.svg', letter: 'k' },
    { name: 'Kerze', url: '/images/kerze.svg', letter: 'k' },
    { name: 'Lehrerin', url: '/images/lehrerin.svg', letter: 'l' },
    { name: 'Lutscher', url: '/images/lutscher.svg', letter: 'l' },
    { name: 'Löffel', url: '/images/loeffel.svg', letter: 'l' },
    { name: 'Luftballon', url: '/images/luftballon.svg', letter: 'l' },
    { name: 'Leiter', url: '/images/leiter.svg', letter: 'l' },
    { name: 'Mund', url: '/images/mund.svg', letter: 'm' },
    { name: 'Malerin', url: '/images/malerin.svg', letter: 'm' },
    { name: 'Maus', url: '/images/maus.svg', letter: 'm' },
    { name: 'Melone', url: '/images/melone.svg', letter: 'm' },
    { name: 'Mond', url: '/images/mond.svg', letter: 'm' },
    { name: 'Nikolaus', url: '/images/nikolaus.svg', letter: 'n' },
    { name: 'Nashorn', url: '/images/nashorn.svg', letter: 'n' },
    { name: 'Nilpferd', url: '/images/nilpferd.svg', letter: 'n' },
    { name: 'Nadel', url: '/images/nadel.svg', letter: 'n' },
    { name: 'Oma', url: '/images/oma.svg', letter: 'o' },
    { name: 'Opa', url: '/images/opa.svg', letter: 'o' },
    { name: 'Ohr', url: '/images/ohr.svg', letter: 'o' },
    { name: 'Polizistin', url: '/images/polizistin.svg', letter: 'p' },
    { name: 'Prinzessin', url: '/images/prinzessin.svg', letter: 'p' },
    { name: 'Pinguin', url: '/images/pinguin.svg', letter: 'p' },
    { name: 'Papagei', url: '/images/papagei.svg', letter: 'p' },
    { name: 'Palme', url: '/images/palme.svg', letter: 'p' },
    { name: 'Paprika', url: '/images/paprika.svg', letter: 'p' },
    { name: 'Pilz', url: '/images/pilz.svg', letter: 'p' },
    { name: 'Pommes', url: '/images/pommes.svg', letter: 'p' },
    { name: 'Pizza', url: '/images/pizza.svg', letter: 'p' },
    { name: 'Puzzleteil', url: '/images/puzzleteil.svg', letter: 'p' },
    { name: 'Pinsel', url: '/images/pinsel.svg', letter: 'p' },
    { name: 'Pflaster', url: '/images/pflaster.svg', letter: 'pf' },
    { name: 'Pfau', url: '/images/pfau.svg', letter: 'pf' },
    { name: 'Qualle', url: '/images/qualle.svg', letter: 'q' },
    { name: 'reiten', url: '/images/reiten.svg', letter: 'r' },
    { name: 'Riesenrad', url: '/images/riesenrad.svg', letter: 'r' },
    { name: 'Roller', url: '/images/roller.svg', letter: 'r' },
    { name: 'Regen', url: '/images/regen.svg', letter: 'r' },
    { name: 'Regenbogen', url: '/images/regenbogen.svg', letter: 'r' },
    { name: 'Regenschirm', url: '/images/regenschirm.svg', letter: 'r' },
    { name: 'Seilbahn', url: '/images/seilbahn.svg', letter: 's' },
    { name: 'Sonne', url: '/images/sonne.svg', letter: 's' },
    { name: 'Socken', url: '/images/socken.svg', letter: 's' },
    { name: 'Säge', url: '/images/saege.svg', letter: 's' },
    { name: 'Seife', url: '/images/seife.svg', letter: 's' },
    { name: 'Stern', url: '/images/stern.svg', letter: 'st' },
    { name: 'Stift', url: '/images/stift.svg', letter: 'st' },
    { name: 'Stuhl', url: '/images/stuhl.svg', letter: 'st' },
    { name: 'Spinne', url: '/images/spinne.svg', letter: 'sp' },
    { name: 'schlafen', url: '/images/schlafen.svg', letter: 's' },
    { name: 'Schwein', url: '/images/schwein.svg', letter: 'sch' },
    { name: 'Schaf', url: '/images/schaf.svg', letter: 'sch' },
    { name: 'Schildkröte', url: '/images/schildkroete.svg', letter: 'sch' },
    { name: 'Schlange', url: '/images/schlange.svg', letter: 'sch' },
    { name: 'Schnecke', url: '/images/schnecke.svg', letter: 'sch' },
    { name: 'Schmetterling', url: '/images/schmetterling.svg', letter: 'sch' },
    { name: 'Schnee', url: '/images/schnee.svg', letter: 'sch' },
    { name: 'Schneemann', url: '/images/schneemann.svg', letter: 'sch' },
    { name: 'Schuhe', url: '/images/schuhe.svg', letter: 'sch' },
    { name: 'Schere', url: '/images/schere.svg', letter: 'sch' },
    { name: 'Traktor', url: '/images/traktor.svg', letter: 't' },
    { name: 'Teddybär', url: '/images/teddybaer.svg', letter: 't' },
    { name: 'Tasche', url: '/images/tasche.svg', letter: 't' },
    { name: 'Trompete', url: '/images/trompete.svg', letter: 't' },
    { name: 'Trommel', url: '/images/trommel.svg', letter: 't' },
    { name: 'Tür', url: '/images/tuer.svg', letter: 't' },
    { name: 'Uhr', url: '/images/uhr.svg', letter: 'u' },
    { name: 'Vogel', url: '/images/vogel.svg', letter: 'v' },
    { name: 'weinen', url: '/images/weinen.svg', letter: 'w' },
    { name: 'Wal', url: '/images/wal.svg', letter: 'w' },
    { name: 'Wolke', url: '/images/wolke.svg', letter: 'w' },
    { name: 'Weihnachtsbaum', url: '/images/weihnachtsbaum.svg', letter: 'w' },
    { name: 'Würfel', url: '/images/wuerfel.svg', letter: 'w' },
    { name: 'Zitrone', url: '/images/zitrone.svg', letter: 'z' },
    { name: 'Zug', url: '/images/zug.svg', letter: 'z' },
    { name: 'Zebra', url: '/images/zebra.svg', letter: 'z' },
    { name: 'Zahnbürste', url: '/images/zahnbuerste.svg', letter: 'z' },
    
    // Ä, Ö, Ü Wörter
    { name: 'Äpfel', url: '/images/aepfel.svg', letter: 'ä' },
    { name: 'Ärger', url: '/images/aerger.svg', letter: 'ä' },
    // { name: 'Öl', url: '/images/oel.svg', letter: 'ö' },
    // { name: 'Ökopark', url: '/images/oekopark.svg', letter: 'ö' },
    // { name: 'Über', url: '/images/ueber.svg', letter: 'ü' },
    // { name: 'Übung', url: '/images/uebung.svg', letter: 'ü' }
];

export const ALL_LETTERS = [
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 
    'Ä', 'Ö', 'Ü', 
    'Eu', 'Ei', 'St', 'Sp', 'Sch', 'Pf'
];

export const VOWELS = ['A', 'E', 'I', 'O', 'U'];
// export const VOWELS = ['A', 'E', 'I', 'O', 'U', 'Ä', 'Ö', 'Ü'];