import { ImageData } from '../types';
import { getPublicImageUrl } from './imageUtils';

export const IMAGES: ImageData[] = [
    { name: 'Affe', url: getPublicImageUrl('affe.svg'), letter: 'a' },
    { name: 'Ananas', url: getPublicImageUrl('ananas.svg'), letter: 'a' },
    { name: 'Apfel', url: getPublicImageUrl('apfel.svg'), letter: 'a' },
    { name: 'Ampel', url: getPublicImageUrl('ampel.svg'), letter: 'a' },
    { name: 'Anker', url: getPublicImageUrl('anker.svg'), letter: 'a' },
    { name: 'Auto', url: getPublicImageUrl('auto.svg'), letter: 'au' },
    { name: 'Ärztin', url: getPublicImageUrl('aerztin.svg'), letter: 'ä' },
    { name: 'Blume', url: getPublicImageUrl('blume.svg'), letter: 'b' },
    { name: 'Baum', url: getPublicImageUrl('baum.svg'), letter: 'b' },
    { name: 'Banane', url: getPublicImageUrl('banane.svg'), letter: 'b' },
    { name: 'Birne', url: getPublicImageUrl('birne.svg'), letter: 'b' },
    { name: 'Brot', url: getPublicImageUrl('brot.svg'), letter: 'b' },
    { name: 'Brezel', url: getPublicImageUrl('brezel.svg'), letter: 'b' },
    { name: 'Berg', url: getPublicImageUrl('berg.svg'), letter: 'b' },
    { name: 'Bus', url: getPublicImageUrl('bus.svg'), letter: 'b' },
    { name: 'Blitz', url: getPublicImageUrl('blitz.svg'), letter: 'b' },
    { name: 'Brille', url: getPublicImageUrl('brille.svg'), letter: 'b' },
    { name: 'Bett', url: getPublicImageUrl('bett.svg'), letter: 'b' },
    { name: 'Clown', url: getPublicImageUrl('clown.svg'), letter: 'c' },
    { name: 'Drache', url: getPublicImageUrl('drache.svg'), letter: 'd' },
    { name: 'Dinosaurier', url: getPublicImageUrl('dinosaurier.svg'), letter: 'd' },
    { name: 'Elefant', url: getPublicImageUrl('elefant.svg'), letter: 'e' },
    { name: 'Ente', url: getPublicImageUrl('ente.svg'), letter: 'e' },
    { name: 'Erdbeere', url: getPublicImageUrl('erdbeere.svg'), letter: 'e' },
    { name: 'Eule', url: getPublicImageUrl('eule.svg'), letter: 'eu' },
    { name: 'Einhorn', url: getPublicImageUrl('einhorn.svg'), letter: 'ei' },
    { name: 'Eisbär', url: getPublicImageUrl('eisbaer.svg'), letter: 'ei' },
    { name: 'Ei', url: getPublicImageUrl('ei.svg'), letter: 'ei' },
    { name: 'Eis', url: getPublicImageUrl('eis.svg'), letter: 'ei' },
    { name: 'Eimer', url: getPublicImageUrl('eimer.svg'), letter: 'ei' },
    { name: 'Feuerwehrfrau', url: getPublicImageUrl('feuerwehrfrau.svg'), letter: 'f' },
    { name: 'Füße', url: getPublicImageUrl('fuesse.svg'), letter: 'f' },
    { name: 'Fuchs', url: getPublicImageUrl('fuchs.svg'), letter: 'f' },
    { name: 'Flamingo', url: getPublicImageUrl('flamingo.svg'), letter: 'f' },
    { name: 'Flügel', url: getPublicImageUrl('fluegel.svg'), letter: 'f' },
    { name: 'Frosch', url: getPublicImageUrl('frosch.svg'), letter: 'f' },
    { name: 'Fisch', url: getPublicImageUrl('fisch.svg'), letter: 'f' },
    { name: 'Feuerwehr', url: getPublicImageUrl('feuerwehr.svg'), letter: 'f' },
    { name: 'Fahrrad', url: getPublicImageUrl('fahrrad.svg'), letter: 'f' },
    { name: 'Flugzeug', url: getPublicImageUrl('flugzeug.svg'), letter: 'f' },
    { name: 'Fußball', url: getPublicImageUrl('fussball.svg'), letter: 'f' },
    { name: 'Fächer', url: getPublicImageUrl('faecher.svg'), letter: 'f' },
    { name: 'Fenster', url: getPublicImageUrl('fenster.svg'), letter: 'f' },
    { name: 'Gespenst', url: getPublicImageUrl('gespenst.svg'), letter: 'g' },
    { name: 'Giraffe', url: getPublicImageUrl('giraffe.svg'), letter: 'g' },
    { name: 'Geschenk', url: getPublicImageUrl('geschenk.svg'), letter: 'g' },
    { name: 'Geldbeutel', url: getPublicImageUrl('geldbeutel.svg'), letter: 'g' },
    { name: 'Glocke', url: getPublicImageUrl('glocke.svg'), letter: 'g' },
    { name: 'Geige', url: getPublicImageUrl('geige.svg'), letter: 'g' },
    { name: 'Herz', url: getPublicImageUrl('herz.svg'), letter: 'h' },
    { name: 'Hand', url: getPublicImageUrl('hand.svg'), letter: 'h' },
    { name: 'Hund', url: getPublicImageUrl('hund.svg'), letter: 'h' },
    { name: 'Hirsch', url: getPublicImageUrl('hirsch.svg'), letter: 'h' },
    { name: 'Hase', url: getPublicImageUrl('hase.svg'), letter: 'h' },
    { name: 'Huhn', url: getPublicImageUrl('huhn.svg'), letter: 'h' },
    { name: 'Heidelbeere', url: getPublicImageUrl('heidelbeere.svg'), letter: 'h' },
    { name: 'Haus', url: getPublicImageUrl('haus.svg'), letter: 'h' },
    { name: 'Hubschrauber', url: getPublicImageUrl('hubschrauber.svg'), letter: 'h' },
    { name: 'Hose', url: getPublicImageUrl('hose.svg'), letter: 'h' },
    { name: 'Hut', url: getPublicImageUrl('hut.svg'), letter: 'h' },
    { name: 'Handy', url: getPublicImageUrl('handy.svg'), letter: 'h' },
    { name: 'Hammer', url: getPublicImageUrl('hammer.svg'), letter: 'h' },
    { name: 'Igel', url: getPublicImageUrl('igel.svg'), letter: 'i' },
    { name: 'Insel', url: getPublicImageUrl('insel.svg'), letter: 'i' },
    { name: 'jonglieren', url: getPublicImageUrl('jonglieren.svg'), letter: 'j' },
    { name: 'krank', url: getPublicImageUrl('krank.svg'), letter: 'k' },
    { name: 'kalt', url: getPublicImageUrl('kalt.svg'), letter: 'k' },
    { name: 'Köchin', url: getPublicImageUrl('koechin.svg'), letter: 'k' },
    { name: 'Katze', url: getPublicImageUrl('katze.svg'), letter: 'k' },
    { name: 'Kuh', url: getPublicImageUrl('kuh.svg'), letter: 'k' },
    { name: 'Känguru', url: getPublicImageUrl('kaenguru.svg'), letter: 'k' },
    { name: 'Krähe', url: getPublicImageUrl('kraehe.svg'), letter: 'k' },
    { name: 'Krokodil', url: getPublicImageUrl('krokodil.svg'), letter: 'k' },
    { name: 'Kaktus', url: getPublicImageUrl('kaktus.svg'), letter: 'k' },
    { name: 'Kirsche', url: getPublicImageUrl('kirsche.svg'), letter: 'k' },
    { name: 'Käse', url: getPublicImageUrl('kaese.svg'), letter: 'k' },
    { name: 'Kuchen', url: getPublicImageUrl('kuchen.svg'), letter: 'k' },
    { name: 'Kaffee', url: getPublicImageUrl('kaffee.svg'), letter: 'k' },
    { name: 'Kirche', url: getPublicImageUrl('kirche.svg'), letter: 'k' },
    { name: 'Kleid', url: getPublicImageUrl('kleid.svg'), letter: 'k' },
    { name: 'Krone', url: getPublicImageUrl('krone.svg'), letter: 'k' },
    { name: 'Kopfhörer', url: getPublicImageUrl('kopfhoerer.svg'), letter: 'k' },
    { name: 'Kerze', url: getPublicImageUrl('kerze.svg'), letter: 'k' },
    { name: 'Lehrerin', url: getPublicImageUrl('lehrerin.svg'), letter: 'l' },
    { name: 'Lutscher', url: getPublicImageUrl('lutscher.svg'), letter: 'l' },
    { name: 'Löffel', url: getPublicImageUrl('loeffel.svg'), letter: 'l' },
    { name: 'Luftballon', url: getPublicImageUrl('luftballon.svg'), letter: 'l' },
    { name: 'Leiter', url: getPublicImageUrl('leiter.svg'), letter: 'l' },
    { name: 'Mund', url: getPublicImageUrl('mund.svg'), letter: 'm' },
    { name: 'Malerin', url: getPublicImageUrl('malerin.svg'), letter: 'm' },
    { name: 'Maus', url: getPublicImageUrl('maus.svg'), letter: 'm' },
    { name: 'Melone', url: getPublicImageUrl('melone.svg'), letter: 'm' },
    { name: 'Mond', url: getPublicImageUrl('mond.svg'), letter: 'm' },
    { name: 'Nikolaus', url: getPublicImageUrl('nikolaus.svg'), letter: 'n' },
    { name: 'Nashorn', url: getPublicImageUrl('nashorn.svg'), letter: 'n' },
    { name: 'Nilpferd', url: getPublicImageUrl('nilpferd.svg'), letter: 'n' },
    { name: 'Nadel', url: getPublicImageUrl('nadel.svg'), letter: 'n' },
    { name: 'Oma', url: getPublicImageUrl('oma.svg'), letter: 'o' },
    { name: 'Opa', url: getPublicImageUrl('opa.svg'), letter: 'o' },
    { name: 'Ohr', url: getPublicImageUrl('ohr.svg'), letter: 'o' },
    { name: 'Polizistin', url: getPublicImageUrl('polizistin.svg'), letter: 'p' },
    { name: 'Prinzessin', url: getPublicImageUrl('prinzessin.svg'), letter: 'p' },
    { name: 'Pinguin', url: getPublicImageUrl('pinguin.svg'), letter: 'p' },
    { name: 'Papagei', url: getPublicImageUrl('papagei.svg'), letter: 'p' },
    { name: 'Palme', url: getPublicImageUrl('palme.svg'), letter: 'p' },
    { name: 'Paprika', url: getPublicImageUrl('paprika.svg'), letter: 'p' },
    { name: 'Pilz', url: getPublicImageUrl('pilz.svg'), letter: 'p' },
    { name: 'Pommes', url: getPublicImageUrl('pommes.svg'), letter: 'p' },
    { name: 'Pizza', url: getPublicImageUrl('pizza.svg'), letter: 'p' },
    { name: 'Puzzleteil', url: getPublicImageUrl('puzzleteil.svg'), letter: 'p' },
    { name: 'Pinsel', url: getPublicImageUrl('pinsel.svg'), letter: 'p' },
    { name: 'Pflaster', url: getPublicImageUrl('pflaster.svg'), letter: 'pf' },
    { name: 'Pfau', url: getPublicImageUrl('pfau.svg'), letter: 'pf' },
    { name: 'Qualle', url: getPublicImageUrl('qualle.svg'), letter: 'q' },
    { name: 'reiten', url: getPublicImageUrl('reiten.svg'), letter: 'r' },
    { name: 'Riesenrad', url: getPublicImageUrl('riesenrad.svg'), letter: 'r' },
    { name: 'Roller', url: getPublicImageUrl('roller.svg'), letter: 'r' },
    { name: 'Regen', url: getPublicImageUrl('regen.svg'), letter: 'r' },
    { name: 'Regenbogen', url: getPublicImageUrl('regenbogen.svg'), letter: 'r' },
    { name: 'Regenschirm', url: getPublicImageUrl('regenschirm.svg'), letter: 'r' },
    { name: 'Seilbahn', url: getPublicImageUrl('seilbahn.svg'), letter: 's' },
    { name: 'Sonne', url: getPublicImageUrl('sonne.svg'), letter: 's' },
    { name: 'Socken', url: getPublicImageUrl('socken.svg'), letter: 's' },
    { name: 'Säge', url: getPublicImageUrl('saege.svg'), letter: 's' },
    { name: 'Seife', url: getPublicImageUrl('seife.svg'), letter: 's' },
    { name: 'Stern', url: getPublicImageUrl('stern.svg'), letter: 'st' },
    { name: 'Stift', url: getPublicImageUrl('stift.svg'), letter: 'st' },
    { name: 'Stuhl', url: getPublicImageUrl('stuhl.svg'), letter: 'st' },
    { name: 'Spinne', url: getPublicImageUrl('spinne.svg'), letter: 'sp' },
    { name: 'schlafen', url: getPublicImageUrl('schlafen.svg'), letter: 's' },
    { name: 'Schwein', url: getPublicImageUrl('schwein.svg'), letter: 'sch' },
    { name: 'Schaf', url: getPublicImageUrl('schaf.svg'), letter: 'sch' },
    { name: 'Schildkröte', url: getPublicImageUrl('schildkroete.svg'), letter: 'sch' },
    { name: 'Schlange', url: getPublicImageUrl('schlange.svg'), letter: 'sch' },
    { name: 'Schnecke', url: getPublicImageUrl('schnecke.svg'), letter: 'sch' },
    { name: 'Schmetterling', url: getPublicImageUrl('schmetterling.svg'), letter: 'sch' },
    { name: 'Schnee', url: getPublicImageUrl('schnee.svg'), letter: 'sch' },
    { name: 'Schneemann', url: getPublicImageUrl('schneemann.svg'), letter: 'sch' },
    { name: 'Schuhe', url: getPublicImageUrl('schuhe.svg'), letter: 'sch' },
    { name: 'Schere', url: getPublicImageUrl('schere.svg'), letter: 'sch' },
    { name: 'Traktor', url: getPublicImageUrl('traktor.svg'), letter: 't' },
    { name: 'Teddybär', url: getPublicImageUrl('teddybaer.svg'), letter: 't' },
    { name: 'Tasche', url: getPublicImageUrl('tasche.svg'), letter: 't' },
    { name: 'Trompete', url: getPublicImageUrl('trompete.svg'), letter: 't' },
    { name: 'Trommel', url: getPublicImageUrl('trommel.svg'), letter: 't' },
    { name: 'Tür', url: getPublicImageUrl('tuer.svg'), letter: 't' },
    { name: 'Uhr', url: getPublicImageUrl('uhr.svg'), letter: 'u' },
    { name: 'Vogel', url: getPublicImageUrl('vogel.svg'), letter: 'v' },
    { name: 'weinen', url: getPublicImageUrl('weinen.svg'), letter: 'w' },
    { name: 'Wal', url: getPublicImageUrl('wal.svg'), letter: 'w' },
    { name: 'Wolke', url: getPublicImageUrl('wolke.svg'), letter: 'w' },
    { name: 'Weihnachtsbaum', url: getPublicImageUrl('weihnachtsbaum.svg'), letter: 'w' },
    { name: 'Würfel', url: getPublicImageUrl('wuerfel.svg'), letter: 'w' },
    { name: 'Zitrone', url: getPublicImageUrl('zitrone.svg'), letter: 'z' },
    { name: 'Zug', url: getPublicImageUrl('zug.svg'), letter: 'z' },
    { name: 'Zebra', url: getPublicImageUrl('zebra.svg'), letter: 'z' },
    { name: 'Zahnbürste', url: getPublicImageUrl('zahnbuerste.svg'), letter: 'z' },
    
    // Ä, Ö, Ü Wörter
    { name: 'Äpfel', url: getPublicImageUrl('aepfel.svg'), letter: 'ä' },
    { name: 'Ärger', url: getPublicImageUrl('aerger.svg'), letter: 'ä' },
    // { name: 'Öl', url: getPublicImageUrl('oel.svg'), letter: 'ö' },
    // { name: 'Ökopark', url: getPublicImageUrl('oekopark.svg'), letter: 'ö' },
    // { name: 'Über', url: getPublicImageUrl('ueber.svg'), letter: 'ü' },
    // { name: 'Übung', url: getPublicImageUrl('uebung.svg'), letter: 'ü' }
];

export const ALL_LETTERS = [
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 
    'Ä', 'Ö', 'Ü', 
    'Eu', 'Ei', 'St', 'Sp', 'Sch', 'Pf'
];

export const VOWELS = ['A', 'E', 'I', 'O', 'U'];
// export const VOWELS = ['A', 'E', 'I', 'O', 'U', 'Ä', 'Ö', 'Ü'];